[dbservers]
proxmox_db ansible_host=9.9.9.230 ansible_user=vinh ansible_password=VFS@2025

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
ansible_become=true
ansible_become_method=sudo
ansible_become_password=VFS@2025
