- hosts: localhost
  gather_facts: no
  vars:
    message: "default message"
  tasks:
    - name: Send Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ chat_id }}"
          text: "{{ message }}"
