- hosts: localhost
  gather_facts: no
  tasks:
    - name: Send Telegram test
      uri:
        url: "https://api.telegram.org/bot{{ telegram_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ chat_id }}"
          text: "🔥 Test từ AWX thành công"
